/*
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *                   NOTICE
 *
 * This software was produced for the U. S. Government
 * under Basic Contract No. FA8702-17-C-0001, and is
 * subject to the Rights in Noncommercial Computer Software
 * and Noncommercial Computer Software Documentation
 * Clause 252.227-7014 (MAY 2013)
 *
 * (c)2016-2017 The MITRE Corporation. All Rights Reserved.
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

package org.mitre.tangerine.reasoner;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 20 14:32:55 EST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int STRING_LITERAL = 26;
    public static final int OPEN_PAREN = 34;
    public static final int RIGHT_BRACKET = 31;
    public static final int GOAL_DECL = 21;
    public static final int DIRINSTANCEOF = 16;
    public static final int NAMESPACE = 25;
    public static final int PERIOD = 22;
    public static final int COMMENT = 36;
    public static final int SUBCLASSOF = 17;
    public static final int RETRACT = 4;
    public static final int PDEF_LINK = 3;
    public static final int GREATER_THAN_EQ = 8;
    public static final int GREATER_THAN = 7;
    public static final int BAR = 39;
    public static final int INSTANCEOF = 15;
    public static final int LEFT_BRACES = 32;
    public static final int NOT = 23;
    public static final int CLOSE_PAREN = 35;
    public static final int LESS_THAN_EQ = 6;
    public static final int SETOF = 37;
    public static final int COMMA = 28;
    public static final int RIGHT_BRACES = 33;
    public static final int EOF = 0;
    public static final int LINK = 2;
    public static final int error = 1;
    public static final int SUBPROPERTYOF = 18;
    public static final int SEMI_COLON = 29;
    public static final int LENGTHOF = 38;
    public static final int NUMBER = 27;
    public static final int SAMEAS = 14;
    public static final int EQ = 9;
    public static final int RULE_DECL = 20;
    public static final int VARIABLE = 12;
    public static final int NE = 10;
    public static final int AT = 11;
    public static final int LESS_THAN = 5;
    public static final int ATTRIBUTE = 13;
    public static final int LEFT_BRACKET = 30;
    public static final int DIRSUBCLASSOF = 19;
    public static final int ALPHA = 24;
}

